/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/contact/Breadcrumb.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    CategorySidebar: typeof import('./src/components/home/CategorySidebar.vue')['default']
    Checkbox: typeof import('./src/components/ui/Checkbox.vue')['default']
    CollapsibleSection: typeof import('./src/components/CollapsibleSection.vue')['default']
    CompanyProfile: typeof import('./src/components/home/CompanyProfile.vue')['default']
    ContactForm: typeof import('./src/components/contact/ContactForm.vue')['default']
    ContactInfo: typeof import('./src/components/contact/ContactInfo.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElementPlusTest: typeof import('./src/components/ElementPlusTest.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FadeTransition: typeof import('./src/components/ui/FadeTransition.vue')['default']
    FilterSection: typeof import('./src/components/FilterSection.vue')['default']
    FilterSidebar: typeof import('./src/components/FilterSidebar.vue')['default']
    FloatingButtons: typeof import('./src/components/contact/FloatingButtons.vue')['default']
    FloatingContact: typeof import('./src/components/home/FloatingContact.vue')['default']
    Footer: typeof import('./src/components/contact/Footer.vue')['default']
    Header: typeof import('./src/components/contact/Header.vue')['default']
    Hero: typeof import('./src/components/contact/Hero.vue')['default']
    HeroSlider: typeof import('./src/components/home/HeroSlider.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    LoadingSpinner: typeof import('./src/components/ui/LoadingSpinner.vue')['default']
    MapSection: typeof import('./src/components/contact/MapSection.vue')['default']
    NewsSection: typeof import('./src/components/home/NewsSection.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductCardSkeleton: typeof import('./src/components/ProductCardSkeleton.vue')['default']
    ProductCategory: typeof import('./src/components/home/ProductCategory.vue')['default']
    ProductRecommend: typeof import('./src/components/home/ProductRecommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    Skeleton: typeof import('./src/components/ui/Skeleton.vue')['default']
  }
}
